version: '3.8'

services:
  app:
    image: ghcr.io/mcpolitics/sp_sim:${TAG:-latest}
    container_name: sp_sim_app
    restart: unless-stopped
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=sp_sim"
      - "org.opencontainers.image.source=https://github.com/mcpolitics/sp_sim"
    networks:
      - sp_sim_network
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  sp_sim_network:
    driver: bridge